version: "3"
services:
  php-fpm:
    image: crazyjums/php-fpm-with-ext
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    ports:
      - 9000:9000
    tty: true
    volumes:
      - ./nginx/html/php_nginx:/var/www/html/php_nginx # 这里存放的php代码，需要和nginx配置文件中root文件夹中文件保持一致